/****************************************************************************************
 * @filename      : 
 * @projectname   : 
 * @author        : i2max.sh.Lee
 * @date          : 2020-05-06
 * @group         :
 * @group-content :
 * @description   :
 * @tester        :
 * @reference     :
 * @copyright     : Copyright © I2max. All Rights Reserved.
 * @modification Log
 * ===============================================================
 * ver     date                     author              description
 * ===============================================================
 0.1     2020-05-06     i2max.sh.Lee          Create
 ****************************************************************************************/

public with sharing class shLogin {

}